version: "3"
services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090 # access Prometheus at http://docker.for.mac.localhost:9090/alerts
    volumes:
      - ./prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules.yml:/etc/prometheus/rules.yml # Mount rules file if you have one
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - localprom
    depends_on: # Prometheus depends on alertmanager being available to send alerts
      - alertmanager
      # Add restart policy if desired
      # restart: unless-stopped

  alertmanager: # <-- New Alertmanager Service
    image: prom/alertmanager
    ports:
      - "9093:9093" # Map host port 9093 to container port 9093. Access AlertManager at http://docker.for.mac.localhost:9093/#/alerts
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml # Mount config file
      - ./alertmanager_data:/alertmanager # Mount data volume for persistence
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--storage.path=/alertmanager" # Explicitly set storage path
    networks:
      - localprom
    # Add restart policy if desired
    # restart: unless-stopped

  grafana:
    image: grafana/grafana
    ports:
      - 3001:3000 # Access Grafana at http://docker.for.mac.localhost:3001/
    volumes:
      - ./grafana_data:/var/lib/grafana
    networks:
      - localprom
    depends_on:
      - prometheus

networks:
  localprom:
    driver: bridge