global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus_service"
    static_configs:
      - targets: [ "docker.for.mac.localhost:9090" ] # macOs

  - job_name: "nodejs_service"
    static_configs:
      - targets: [ "docker.for.mac.localhost:9090" ] # macOs