global:
  scrape_interval: 15s # How often to scrape targets

scrape_configs:
  - job_name: "prometheus_service"
    static_configs:
      - targets: [ "docker.for.mac.localhost:9090" ] # macOs

  - job_name: "petProjectForLearning_service"
    static_configs:
      - targets: [ "host.docker.internal:3000" ] # Use host.docker.internal instead of localhost because prometheus in running in docker and cant access "localhost" of outside docker system. This End point will be checked for "/metrics"API by prometheius. And when available the logs will be polled from here.

rule_files:
  - /etc/prometheus/rules.yml # Path inside the container where rules are mounted

alerting: # <-- Add or ensure this section exists
  alertmanagers:
    - static_configs:
        - targets:
            # Use service name 'alertmanager' and its internal port 9093
            - 'alertmanager:9093'